/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author THIS PC
 */
public class DoiMK extends javax.swing.JInternalFrame {
    private ImageIcon icOff, icOn;
    private boolean showpass;
    /**
     * Creates new form CC
     */
    public DoiMK() {
        initComponents();
        this.icOn = new ImageIcon("src/Image/visibility.png");
        this.icOff = new ImageIcon("src/Image/visibility_lock.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPassCu = new javax.swing.JPasswordField();
        txtPassMoi = new javax.swing.JPasswordField();
        btnDongY = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtXNP = new javax.swing.JPasswordField();
        lbl_show = new javax.swing.JLabel();
        lbl_show1 = new javax.swing.JLabel();
        lbl_show2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Đổi mật khẩu");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("ĐỔI MẬT KHẨU");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tên đăng nhập");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu mới");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mật khẩu hiện tại");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Xác nhận mật khẩu mới");

        btnDongY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Accept.png"))); // NOI18N
        btnDongY.setText("Đồng ý");
        btnDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongYActionPerformed(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/No.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        lbl_show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/visibility.png"))); // NOI18N
        lbl_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_showMouseClicked(evt);
            }
        });

        lbl_show1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/visibility.png"))); // NOI18N
        lbl_show1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_show1MouseClicked(evt);
            }
        });

        lbl_show2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/visibility.png"))); // NOI18N
        lbl_show2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_show2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnDongY)
                                    .addGap(35, 35, 35)
                                    .addComponent(btnHuy)
                                    .addGap(48, 48, 48))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtXNP, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_show)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPassMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_show1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPassCu, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_show2)))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassCu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_show2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_show1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtXNP, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDongY)
                    .addComponent(btnHuy))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_showMouseClicked
        this.showpass = !this.showpass;
        if (this.showpass) {
            this.lbl_show.setIcon(icOff);
            this.txtXNP.setEchoChar((char)0);
        }else{
            this.lbl_show.setIcon(icOn);
            this.txtXNP.setEchoChar('*');
        }
    }//GEN-LAST:event_lbl_showMouseClicked

    private void lbl_show1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_show1MouseClicked
        this.showpass = !this.showpass;
        if (this.showpass) {
            this.lbl_show1.setIcon(icOff);
            this.txtPassMoi.setEchoChar((char)0);
        }else{
            this.lbl_show1.setIcon(icOn);
            this.txtPassMoi.setEchoChar('*');
        }
    }//GEN-LAST:event_lbl_show1MouseClicked

    private void lbl_show2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_show2MouseClicked
        this.showpass = !this.showpass;
        if (this.showpass) {
            this.lbl_show2.setIcon(icOff);
            this.txtPassCu.setEchoChar((char)0);
        }else{
            this.lbl_show2.setIcon(icOn);
            this.txtPassCu.setEchoChar('*');
        }
    }//GEN-LAST:event_lbl_show2MouseClicked

    private boolean check(){
        String PWXN = String.valueOf(this.txtXNP.getPassword());
        String PWM = String.valueOf(this.txtPassMoi.getPassword());
        String PWC = String.valueOf(this.txtPassCu.getPassword());
        if (this.txtTenTK.getText().trim().equals("") || PWC.trim().equals("")
            || PWM.trim().equals("") || PWXN.trim().equals("")
           ) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đẩy đủ thông tin");
            return false;
        }else if(PWC.trim().length() < 3 
                || PWM.trim().length() < 3  || PWXN.trim().length() < 3 ){
            JOptionPane.showMessageDialog(this, "Mật khẩu ít nhất 3 ký tự");
            return false;
        }else if(!PWXN.equals(PWM)){
            JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu không khớp với mật khẩu mới");
            return false;
        }
        try {
            String sql = "SELECT * FROM NhanVien WHERE manv = ? and MatKhau = ?";
            PreparedStatement ps = JDBC.KetNoi.prepare(sql);
            ps.setString(1, this.txtTenTK.getText());
            ps.setString(2, String.valueOf(this.txtPassCu.getPassword()));
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                
            }else{
                JOptionPane.showMessageDialog(this, "Sai tài khoản mật khẩu");
                return false;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
        return true;
    }
    
    private void clear(){
        this.txtPassCu.setText("");
        this.txtPassMoi.setText("");
        this.txtXNP.setText("");
        this.txtTenTK.setText("");
    }
    private void btnDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongYActionPerformed
        if (this.check()) {
            try {
                String sql = "UPDATE NhanVien SET matkhau = ? WHERE manv = ?";
                PreparedStatement ps = JDBC.KetNoi.prepare(sql);
                ps.setString(1, String.valueOf(this.txtPassMoi.getPassword()));
                ps.setString(2, this.txtTenTK.getText());
                ps.execute();
                ResultSet rs = ps.getResultSet();
                this.clear();
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
            } catch (Exception e) {
                e.printStackTrace();
            }
            FormChinh fc = new FormChinh();
            fc.dispose();
            this.dispose();
        }
    }//GEN-LAST:event_btnDongYActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDongY;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_show;
    private javax.swing.JLabel lbl_show1;
    private javax.swing.JLabel lbl_show2;
    private javax.swing.JPasswordField txtPassCu;
    private javax.swing.JPasswordField txtPassMoi;
    private javax.swing.JTextField txtTenTK;
    private javax.swing.JPasswordField txtXNP;
    // End of variables declaration//GEN-END:variables
}
