/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.ChuyenDe_DAO;
import Model.ChuyenDe;
import Model.NhanVien;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THIS PC
 */
public class IF_QLCD extends javax.swing.JInternalFrame {
    private List<ChuyenDe> lstCD;
    private ChuyenDe_DAO CDDAO;
    private DefaultTableModel model;
      private int vitri;
    
    /**
     * Creates new form IF_QLCD
     */
    public IF_QLCD() {
        initComponents();
        this.CDDAO = new ChuyenDe_DAO();
        this.model = (DefaultTableModel) this.tbl_Table.getModel();
        this.getAll();
        this.tab.setSelectedIndex(1);
    }

    private void getAll(){
        this.model.setRowCount(0);
        this.lstCD = this.CDDAO.getAll();
        for (ChuyenDe cd : lstCD) {
            Object [] r = new Object[]{
                cd.getMaCD(),
                cd.getTenCD(),
                cd.getHocPhi(),
                cd.getThoiLuong(),
                cd.getHinh()
            };
            this.model.addRow(r);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaCD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtTenCD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtThoiLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHocPhi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        btn_them = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_anh = new javax.swing.JLabel();
        lbl_tenanh = new javax.swing.JLabel();
        btn_moi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Table = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Quản Lý Chuyên Đề");

        jLabel2.setText("Hình Logo");

        jLabel4.setText("Mã chuyên đề");

        txtMaCD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaCDKeyReleased(evt);
            }
        });

        jLabel5.setText("Tên chuyên đề");

        jLabel6.setText("Thời lượng (giờ)");

        jLabel7.setText("Học phí");

        jLabel8.setText("Mô ta chuyên đề");

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane2.setViewportView(txtMoTa);

        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add to basket.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Notes.png"))); // NOI18N
        btn_update.setText("Sửa");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_last.setText(">|");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        btn_next.setText(">>");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_back.setText("<<");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_first.setText("|<");
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(202, 4));

        lbl_anh.setBackground(new java.awt.Color(102, 51, 255));
        lbl_anh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_anh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_anhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_anh, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_anh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lbl_tenanh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tenanh.setText("Tên hình");

        btn_moi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Unordered list.png"))); // NOI18N
        btn_moi.setText("Mới");
        btn_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(txtMaCD, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addComponent(TxtTenCD)
                            .addComponent(txtThoiLuong)
                            .addComponent(txtHocPhi)))
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_them)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_xoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_moi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btn_first)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_last))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel2)
                                .addGap(107, 107, 107)
                                .addComponent(jLabel4))
                            .addComponent(lbl_tenanh, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMaCD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtTenCD, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_tenanh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_update)
                    .addComponent(btn_xoa)
                    .addComponent(btn_last)
                    .addComponent(btn_next)
                    .addComponent(btn_back)
                    .addComponent(btn_first)
                    .addComponent(btn_moi))
                .addContainerGap())
        );

        tab.addTab("Cập nhật", new javax.swing.ImageIcon(getClass().getResource("/Image/Edit.png")), jPanel2); // NOI18N

        tbl_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã CD", "Tên CD", "Học Phí", "Thời Lượng", "Hình"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        tab.addTab("Danh sách", new javax.swing.ImageIcon(getClass().getResource("/Image/List.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(251, 251, 251))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_anhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_anhMouseClicked
        JFileChooser fc = new JFileChooser("src\\Image");
        int r = fc.showOpenDialog(this);
        if (r == JFileChooser.APPROVE_OPTION) {
            try {
                File file = fc.getSelectedFile(); //lấy file người dùng chọn
                String anh = file.getAbsolutePath();
                ImageIcon icon2 = new ImageIcon(anh);
                Image im = icon2.getImage();
                ImageIcon icon = new ImageIcon(im.getScaledInstance(this.lbl_anh.getWidth(), this.lbl_anh.getHeight(), im.SCALE_SMOOTH));
                // Lấy được tên hình ảnh    
                this.lbl_tenanh.setText(""+fc.getSelectedFile().getName());
                this.lbl_anh.setIcon(icon);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_lbl_anhMouseClicked

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        try {
            for (ChuyenDe cd : lstCD) {
                System.out.println(cd.getMaCD());
                System.out.println(this.txtMaCD.getText());
                if (this.txtMaCD.getText().equals(cd.getMaCD())) {
                    int xn = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa Mã chuyên đề: "+this.txtMaCD.getText(),"Thông Báo", JOptionPane.YES_NO_OPTION);
                    if (xn == 0){
                        this.CDDAO.delete(this.txtMaCD.getText());
                        this.getAll();
                        this.clear();
                        JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    }
                    return;
                }else{
                    continue;
                }
            }
            JOptionPane.showMessageDialog(this, "Mã nhân viên bạn cần xóa không tồn tại!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if (this.check()) {
            try {
                for (ChuyenDe cd : lstCD) {
                    if (this.txtMaCD.getText().equals(cd.getMaCD())) {
                        String macd = this.txtMaCD.getText();
                        int xn = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa Mã Chuyên Đề: "+macd,"Thông Báo", JOptionPane.YES_NO_OPTION);
                        if (xn == 0){
                            String ten = this.TxtTenCD.getText();
                            float hocphi = Float.parseFloat(this.txtHocPhi.getText());;
                            int thoiluong = Integer.parseInt(this.txtThoiLuong.getText());
                            String mota = this.txtMoTa.getText();
                            String tenanh = this.lbl_tenanh.getText();
                            
                            cd = new ChuyenDe(macd, ten, hocphi, thoiluong, tenanh, mota);
                            this.CDDAO.update(cd);
                            JOptionPane.showMessageDialog(this, "Sửa thành công!");
                            this.getAll();
                            this.clear();
                        }
                        return;
                    }else{
                        continue;
                    }
                }
                JOptionPane.showMessageDialog(this, "Mã nhân viên bạn cần sửa không tồn tại!");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
         if (this.check()) {
            try {
                for (ChuyenDe cd : lstCD) {
                    if (this.txtMaCD.getText().equals(cd.getMaCD())) {
                        JOptionPane.showMessageDialog(this, "Mã chuyên đề này đã tồn tại!");
                        return;
                    }
                }
                    String macd = this.txtMaCD.getText();
                    String ten = this.TxtTenCD.getText();
                    double hocphi = Double.parseDouble(this.txtHocPhi.getText());;
                    int thoiluong = Integer.parseInt(this.txtThoiLuong.getText());
                    String mota = this.txtMoTa.getText();
                    String tenanh = this.lbl_tenanh.getText();
                    ChuyenDe cd = new ChuyenDe(macd, ten, hocphi, thoiluong, tenanh, mota);
                    this.CDDAO.insert(cd);
                
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                    this.getAll();
                    this.clear();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_themActionPerformed
    private void showAgain(){
        this.vitri = this.tbl_Table.getSelectedRow();
        if (this.vitri == -1) {
            return;
        }
        this.txtMaCD.setText(this.tbl_Table.getValueAt(vitri, 0).toString());
        this.TxtTenCD.setText(this.tbl_Table.getValueAt(vitri, 1).toString());
        this.txtHocPhi.setText(this.tbl_Table.getValueAt(vitri, 2).toString());
        this.txtThoiLuong.setText(this.tbl_Table.getValueAt(vitri, 3).toString());
        this.lbl_tenanh.setText(this.tbl_Table.getValueAt(vitri, 4).toString());
        this.updateHinh(this.tbl_Table.getValueAt(vitri, 4).toString());
        for (ChuyenDe cd : lstCD) {
            if (this.txtMaCD.getText().equals(cd.getMaCD())) {
                this.txtMoTa.setText(cd.getMoTa());
                return;
            }else{
                continue;
            }
        }
    }
    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
         try {
            this.vitri = 0;
            this.tbl_Table.setRowSelectionInterval(vitri, vitri);
            this.showAgain();
            this.setStatusVitri();
            this.edit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        try {
            this.vitri --;
            if (vitri < 0) {
                this.vitri = 0;
            }
            this.tbl_Table.setRowSelectionInterval(vitri, vitri);
            this.showAgain();
            this.setStatusVitri();
            this.edit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        try {
            this.vitri ++;
            if (vitri > lstCD.size() - 1) {
                this.vitri = lstCD.size() - 1;
            }
            this.tbl_Table.setRowSelectionInterval(vitri, vitri);
            this.showAgain();
            this.setStatusVitri();
            this.edit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
         try {
            this.vitri = lstCD.size() - 1;
            this.tbl_Table.setRowSelectionInterval(vitri, vitri);
            this.showAgain();
            this.setStatusVitri();
            this.edit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moiActionPerformed
        clear();
    }//GEN-LAST:event_btn_moiActionPerformed

    private void updateHinh(String image){
        ImageIcon image1 = new ImageIcon("src\\Image\\" + image);
        Image im = image1.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(this.lbl_anh.getWidth(), this.lbl_anh.getHeight(), im.SCALE_SMOOTH));
        this.lbl_anh.setIcon(icon);
    }
    
    private void tbl_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_TableMouseClicked
        this.showAgain();
        this.tab.setSelectedIndex(0);
        this.setStatusVitri();
        this.edit();
    }//GEN-LAST:event_tbl_TableMouseClicked

    private void txtMaCDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaCDKeyReleased
        this.edit();
    }//GEN-LAST:event_txtMaCDKeyReleased
    
    void setStatusVitri(){
        boolean first = this.vitri <= 0;
        boolean last = this.vitri >= lstCD.size() - 1;
        btn_back.setEnabled(!first);
        btn_first.setEnabled(!first);
        btn_last.setEnabled(!last);
        btn_next.setEnabled(!last);
    }
    
    void edit(){
//        String manv = (String) tbl_Table.getValueAt(this.vitri, 0);
        for (ChuyenDe cd : lstCD) {
            if (this.txtMaCD.getText().equals(cd.getMaCD())) {
                this.btn_them.setEnabled(false);
                this.btn_update.setEnabled(true);
                this.btn_xoa.setEnabled(true);
                break;
            }else{
                this.btn_them.setEnabled(true);
                this.btn_update.setEnabled(false);
                this.btn_xoa.setEnabled(false);
                continue;
            }
        }
    }
    
    void setStatus(boolean insertable){
        this.btn_them.setEnabled(insertable);
        this.btn_update.setEnabled(!insertable);
        this.btn_xoa.setEnabled(!insertable);
        this.btn_last.setEnabled(true);
        this.btn_back.setEnabled(true);
        this.btn_first.setEnabled(true);
        this.btn_next.setEnabled(true);
    }
    
    private void clear(){
        this.txtMaCD.setText("");
        this.TxtTenCD.setText("");
        this.txtHocPhi.setText("");
        this.txtMoTa.setText("");
        this.txtThoiLuong.setText("");
        this.lbl_anh.setText("");
        ImageIcon image1 = new ImageIcon();
        this.lbl_anh.setIcon(image1);
        this.setStatus(true);
    }
    private boolean check(){
        if (this.TxtTenCD.getText().trim().equals("") || this.txtMaCD.getText().trim().equals("") ||
            this.txtMoTa.getText().trim().equals("") ||this.txtHocPhi.getText().trim().equals("") ||
                this.txtThoiLuong.getText().trim().equals("")||this.lbl_tenanh.getText().trim().equals("")    
                ) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!");
            return false;
        }
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtTenCD;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_moi;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_anh;
    private javax.swing.JLabel lbl_tenanh;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tbl_Table;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtMaCD;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtThoiLuong;
    // End of variables declaration//GEN-END:variables
}
