/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.NhanVien_DAO;
import Model.NhanVien;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THIS PC
 */
public class IF_QLNV extends javax.swing.JInternalFrame {
    private List<NhanVien> lstnv;
    private NhanVien_DAO NVDAO;
    private DefaultTableModel model;
    private int vitri;
    /**
     * Creates new form IF_QLNV
     */
    public IF_QLNV() {
        initComponents();
        this.NVDAO = new NhanVien_DAO();
        this.model = (DefaultTableModel) this.tbl_Table.getModel();
        this.getAll();
        this.tab.setSelectedIndex(1);
    }

    private void getAll(){
        this.model.setRowCount(0);
        this.lstnv = this.NVDAO.getAll();
        for (NhanVien nv : lstnv) {
            Object [] r = new Object[]{
                nv.getMaNV(),
                nv.getMatKhau(),
                nv.getHoTen(),
                nv.setVaiTro()
            };
            this.model.addRow(r);
        }
    }
    
    private void clear(){
        this.txt_hoten.setText("");
        this.txt_manv.setText("");
        this.txt_matkhau.setText("");
        this.txt_xnmk.setText("");
        this.rd_nv.setSelected(true);
        this.setStatus(true);
    }
    
    private boolean check(){
        String passs = String.valueOf(this.txt_matkhau.getPassword());
        String XNpasss = String.valueOf(this.txt_xnmk.getPassword());
        if (this.txt_manv.getText().trim().equals("") || this.txt_hoten.getText().trim().equals("") ||
            passs.trim().equals("") || XNpasss.trim().equals("")    
                ) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đầy đủ thông tin!");
            return false;
        }else if(passs.trim().length() < 3 || XNpasss.trim().length() < 3){
            JOptionPane.showMessageDialog(this, "Mật khẩu ít nhất 3 ký tự!");
            return false;
        }else if(!XNpasss.equals(passs)){
            JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu không khớp với mật khẩu!");
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_manv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rd_truongphong = new javax.swing.JRadioButton();
        rd_nv = new javax.swing.JRadioButton();
        btn_them = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        txt_matkhau = new javax.swing.JPasswordField();
        txt_xnmk = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        btn_moi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Table = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Quản Lý Nhiên Viên ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Quản Lý Nhân Viên");

        jLabel2.setText("Mã nhân viên");

        txt_manv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_manvKeyReleased(evt);
            }
        });

        jLabel3.setText("Mật khẩu");

        jLabel4.setText("Xác nhận mật khẩu");

        jLabel5.setText("Họ và Tên");

        jLabel6.setText("Vai trò");

        buttonGroup1.add(rd_truongphong);
        rd_truongphong.setText("Trưởng phòng");

        buttonGroup1.add(rd_nv);
        rd_nv.setSelected(true);
        rd_nv.setText("Nhân viên");

        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Add to basket.png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Notes.png"))); // NOI18N
        btn_update.setText("Sửa");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Delete.png"))); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_last.setText(">|");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        btn_next.setText(">>");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_back.setText("<<");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_first.setText("|<");
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/project.png"))); // NOI18N

        btn_moi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Unordered list.png"))); // NOI18N
        btn_moi.setText("Mới");
        btn_moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rd_truongphong)
                                        .addGap(18, 18, 18)
                                        .addComponent(rd_nv))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_hoten, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_xnmk, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_matkhau, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(80, 80, 80)))
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_them)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_xoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_moi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_first))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 75, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_next)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_last)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_xnmk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd_truongphong)
                    .addComponent(rd_nv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them)
                    .addComponent(btn_update)
                    .addComponent(btn_xoa)
                    .addComponent(btn_last)
                    .addComponent(btn_next)
                    .addComponent(btn_back)
                    .addComponent(btn_first)
                    .addComponent(btn_moi))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tab.addTab("Cập nhật", new javax.swing.ImageIcon(getClass().getResource("/Image/Edit.png")), jPanel2); // NOI18N

        tbl_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Mật Khẩu", "Họ và Tên", "Vai Trò"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        tab.addTab("Danh sách", new javax.swing.ImageIcon(getClass().getResource("/Image/List.png")), jPanel3); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        if (this.check()) {
            try {
                for (NhanVien nv : lstnv) {
                    if (this.txt_manv.getText().equals(nv.getMaNV())) {
                        JOptionPane.showMessageDialog(this, "Mã nhân viên này đã tồn tại!");
                        return;
                    }
                }
                String manv = this.txt_manv.getText();
                String hoten = this.txt_hoten.getText();
                String password = String.valueOf(this.txt_matkhau.getPassword());
                boolean vaitro;
                if (this.rd_truongphong.isSelected()) {
                    vaitro = true;
                }else{
                    vaitro = false;
                }
                
                NhanVien nv = new NhanVien(manv, password, hoten, vaitro);
                this.NVDAO.insert(nv);
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                this.getAll();
                this.clear();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moiActionPerformed
        this.clear();
    }//GEN-LAST:event_btn_moiActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        try {
            for (NhanVien nv : lstnv) {
                if (this.txt_manv.getText().equals(nv.getMaNV())) {
                    int xn = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa Mã Nhân Viên: "+this.txt_manv.getText(),"Thông Báo", JOptionPane.YES_NO_OPTION);
                    if (xn == 0){
                        this.NVDAO.delete(this.txt_manv.getText());
                        this.getAll();
                        this.clear();
                        JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    }
                    return;
                }else{
                    continue;
                }
            }
            JOptionPane.showMessageDialog(this, "Mã nhân viên bạn cần xóa không tồn tại!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        if (this.check()) {
            try {
                for (NhanVien nv : lstnv) {
                    if (this.txt_manv.getText().equals(nv.getMaNV())) {
                        String manv = this.txt_manv.getText();
                        int xn = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa Mã Nhân Viên: "+manv,"Thông Báo", JOptionPane.YES_NO_OPTION);
                        if (xn == 0){
                            String hoten = this.txt_hoten.getText();
                            String password = String.valueOf(this.txt_matkhau.getPassword());
                            boolean vaitro;
                            if (this.rd_truongphong.isSelected()) {
                                vaitro = true;
                            }else{
                                vaitro = false;
                            }

                            nv = new NhanVien(manv, password, hoten, vaitro);
                            this.NVDAO.update(nv);
                            JOptionPane.showMessageDialog(this, "Sửa thành công!");
                            this.getAll();
                            this.clear();
                        }
                        return;
                    }else{
                        continue;
                    }
                }
                JOptionPane.showMessageDialog(this, "Mã nhân viên bạn cần sửa không tồn tại!");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void showAgain(){
        this.vitri = this.tbl_Table.getSelectedRow();
        if (this.vitri == -1) {
            return;
        }
        this.txt_hoten.setText(this.tbl_Table.getValueAt(vitri, 2).toString());
        this.txt_manv.setText(this.tbl_Table.getValueAt(vitri, 0).toString());
        this.txt_matkhau.setText(this.tbl_Table.getValueAt(vitri, 1).toString());
        this.txt_xnmk.setText(String.valueOf(this.txt_matkhau.getPassword()));
        if (this.tbl_Table.getValueAt(vitri, 3).toString().equalsIgnoreCase("Trưởng phòng")) {
            this.rd_truongphong.setSelected(true);
        }else{
            this.rd_nv.setSelected(true);
        }
    }
    
    void setStatusVitri(){
        boolean first = this.vitri <= 0;
        boolean last = this.vitri >= lstnv.size() - 1;
        btn_back.setEnabled(!first);
        btn_first.setEnabled(!first);
        btn_last.setEnabled(!last);
        btn_next.setEnabled(!last);
    }
    
    void edit(){
//        String manv = (String) tbl_Table.getValueAt(this.vitri, 0);
        for (NhanVien nv : lstnv) {
            if (this.txt_manv.getText().equals(nv.getMaNV())) {
                this.btn_them.setEnabled(false);
                this.btn_update.setEnabled(true);
                this.btn_xoa.setEnabled(true);
                break;
            }else{
                this.btn_them.setEnabled(true);
                this.btn_update.setEnabled(false);
                this.btn_xoa.setEnabled(false);
                continue;
            }
        }
    }
    
    void setStatus(boolean insertable){
        this.btn_them.setEnabled(insertable);
        this.btn_update.setEnabled(!insertable);
        this.btn_xoa.setEnabled(!insertable);
        this.btn_last.setEnabled(true);
        this.btn_back.setEnabled(true);
        this.btn_first.setEnabled(true);
        this.btn_next.setEnabled(true);
    }
    
    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        try {
            this.vitri = 0;
            this.tbl_Table.setRowSelectionInterval(vitri, vitri);
            this.showAgain();
            this.setStatusVitri();
            this.edit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_firstActionPerformed

    private void tbl_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_TableMouseClicked
        this.showAgain();
        this.tab.setSelectedIndex(0);
        this.setStatusVitri();
        this.edit();
    }//GEN-LAST:event_tbl_TableMouseClicked

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        try {
            this.vitri --;
            if (vitri < 0) {
                this.vitri = 0;
            }
            this.tbl_Table.setRowSelectionInterval(vitri, vitri);
            this.showAgain();
            this.setStatusVitri();
            this.edit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        try {
            this.vitri ++;
            if (vitri > lstnv.size() - 1) {
                this.vitri = lstnv.size() - 1;
            }
            this.tbl_Table.setRowSelectionInterval(vitri, vitri);
            this.showAgain();
            this.setStatusVitri();
            this.edit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        try {
            this.vitri = lstnv.size() - 1;
            this.tbl_Table.setRowSelectionInterval(vitri, vitri);
            this.showAgain();
            this.setStatusVitri();
            this.edit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void txt_manvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_manvKeyReleased
        this.edit();
    }//GEN-LAST:event_txt_manvKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_moi;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rd_nv;
    private javax.swing.JRadioButton rd_truongphong;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tbl_Table;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_manv;
    private javax.swing.JPasswordField txt_matkhau;
    private javax.swing.JPasswordField txt_xnmk;
    // End of variables declaration//GEN-END:variables
}
